CREATE TABLE `user_tb` (
                           `id`                BIGINT NOT NULL AUTO_INCREMENT,
                           `user_email`        VARCHAR(100) NOT NULL UNIQUE,
                           `user_password`     VARCHAR(100) NOT NULL,
                           `user_name`         VARCHAR(50) NOT NULL,
                           `profile_thumb_url` VARCHAR(255),
                           `position`          VARCHAR(30) NOT NULL,
                           `phone_number`      VARCHAR(20) NOT NULL UNIQUE,
                           `used_vacation`     INT UNSIGNED NOT NULL,
                           `created_at`         DATETIME NOT NULL default now(),
                           `updated_at`         DATETIME NOT NULL  default now() on update now(),
                           PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE `refresh_token_tb` (
                                    `id`       BIGINT NOT NULL AUTO_INCREMENT,
                                    `user_id`  BIGINT NOT NULL UNIQUE,
                                    `refresh_token_id`    VARCHAR(20) NOT NULL,
                                    PRIMARY KEY (`id`, `user_id`),
                                    FOREIGN KEY (`user_id`) REFERENCES `user_tb` (`id`)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE `signin_log_tb` (
                                 `id`          BIGINT NOT NULL AUTO_INCREMENT,
                                 `user_id`     BIGINT NOT NULL,
                                 `ip_address`  VARCHAR(45) NOT NULL,
                                 `user_agent`  VARCHAR(255) NOT NULL,
                                 `created_at`   DATETIME NOT NULL default now(),
                                 PRIMARY KEY (`id`, `user_id`),
                                 FOREIGN KEY (`user_id`) REFERENCES `user_tb` (`id`)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE `schedule_tb` (
                               `id`            BIGINT NOT NULL AUTO_INCREMENT,
                               `user_id`       BIGINT NOT NULL,
                               `schedule_type`  VARCHAR(20) NOT NULL,
                               `state`         VARCHAR(20) NOT NULL,
                               `start_date`    TIMESTAMP(9) NOT NULL,
                               `end_date`      TIMESTAMP(9) NOT NULL,
                               `created_at`     DATETIME NOT NULL default now(),
                               `updated_at`     DATETIME NOT NULL  default now() on update now(),
                               PRIMARY KEY (`id`),
                               FOREIGN KEY (`user_id`) REFERENCES `user_tb` (`id`)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE BATCH_JOB_INSTANCE  (
                                     JOB_INSTANCE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                     VERSION BIGINT ,
                                     JOB_NAME VARCHAR(100) NOT NULL,
                                     JOB_KEY VARCHAR(32) NOT NULL,
                                     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
                                      JOB_EXECUTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                      VERSION BIGINT  ,
                                      JOB_INSTANCE_ID BIGINT NOT NULL,
                                      CREATE_TIME TIMESTAMP NOT NULL,
                                      START_TIME TIMESTAMP DEFAULT NULL ,
                                      END_TIME TIMESTAMP DEFAULT NULL ,
                                      STATUS VARCHAR(10) ,
                                      EXIT_CODE VARCHAR(2500) ,
                                      EXIT_MESSAGE VARCHAR(2500) ,
                                      LAST_UPDATED TIMESTAMP,
                                      JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
                                      constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                          references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID BIGINT NOT NULL ,
                                             TYPE_CD VARCHAR(6) NOT NULL ,
                                             KEY_NAME VARCHAR(100) NOT NULL ,
                                             STRING_VAL VARCHAR(250) ,
                                             DATE_VAL TIMESTAMP DEFAULT NULL ,
                                             LONG_VAL BIGINT ,
                                             DOUBLE_VAL DOUBLE PRECISION ,
                                             IDENTIFYING CHAR(1) NOT NULL ,
                                             constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                 references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
                                       STEP_EXECUTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                       VERSION BIGINT NOT NULL,
                                       STEP_NAME VARCHAR(100) NOT NULL,
                                       JOB_EXECUTION_ID BIGINT NOT NULL,
                                       START_TIME TIMESTAMP NOT NULL ,
                                       END_TIME TIMESTAMP DEFAULT NULL ,
                                       STATUS VARCHAR(10) ,
                                       COMMIT_COUNT BIGINT ,
                                       READ_COUNT BIGINT ,
                                       FILTER_COUNT BIGINT ,
                                       WRITE_COUNT BIGINT ,
                                       READ_SKIP_COUNT BIGINT ,
                                       WRITE_SKIP_COUNT BIGINT ,
                                       PROCESS_SKIP_COUNT BIGINT ,
                                       ROLLBACK_COUNT BIGINT ,
                                       EXIT_CODE VARCHAR(2500) ,
                                       EXIT_MESSAGE VARCHAR(2500) ,
                                       LAST_UPDATED TIMESTAMP,
                                       constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                           references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
                                               STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                               SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                               SERIALIZED_CONTEXT LONGVARCHAR ,
                                               constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                   references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
                                              JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT LONGVARCHAR ,
                                              constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_JOB_SEQ;
